name: Deploy to Github Pages

on:
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_OMDB_API_KEY: ${{ secrets.VITE_OMDB_API_KEY }}
          VITE_KINOPOISK_API_KEY: ${{ secrets.VITE_KINOPOISK_API_KEY }}
          BASE_URL: /otus-js-b-course-project
      - name: Copy static assets
        run: cp ./apple-touch-icon.png ./favicon-*.png ./android-chrome-*.png ./favicon.ico ./site.webmanifest ./dist/
      - name: Fix SPA routing
        run: cp ./dist/index.html ./dist/404.html
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
